=== dertom95/thepipe/plugins/xsd/thepipeline.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://thepipeline.com" xmlns="https://thepipeline.com" elementFormDefault="qualified">
	<xs:simpleType name="tooltype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="cli"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="targettype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="psx"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="hosttype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="linux"/>
					<xs:enumeration value="linux-arm"/>
					<xs:enumeration value="macos"/>
					<xs:enumeration value="win"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="paramtype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bool"/>
					<xs:enumeration value="enum[]"/>
					<xs:enumeration value="file"/>
					<xs:enumeration value="vec[2]"/>
					<xs:enumeration value="vec[3]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="booltype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false"/>
					<xs:enumeration value="true"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:element name="thepipeline">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="converter">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="command">
								<xs:complexType>
									<xs:attribute name="arguments" type="xs:string" use="required"/>
									<xs:attribute name="extension" type="xs:string"/>
									<xs:attribute name="metafiles" type="xs:string"/>
									<xs:attribute name="toolid" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="parameters">
								<xs:complexType>
									<xs:choice minOccurs="0" maxOccurs="unbounded">
										<xs:element name="param">
											<xs:complexType>
												<xs:attribute name="description" type="xs:string"/>
												<xs:attribute name="id" type="xs:string" use="required"/>
												<xs:attribute name="output" type="xs:string" use="required"/>
												<xs:attribute name="required" type="booltype"/>
												<xs:attribute name="type" type="paramtype" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="rip">
											<xs:complexType>
												<xs:attribute name="required" type="booltype"/>
												<xs:attribute name="type" type="paramtype" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="prefix" type="xs:string" use="required"/>
						<xs:attribute name="target" type="targettype"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="tool">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="command">
								<xs:complexType>
									<xs:choice minOccurs="0" maxOccurs="unbounded">
										<xs:element name="rip">
											<xs:complexType>
												<xs:attribute name="host" type="hosttype"/>
											</xs:complexType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="file" type="xs:string"/>
									<xs:attribute name="host" type="hosttype"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="target" type="targettype"/>
						<xs:attribute name="type" type="tooltype" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dertom95/thepipe/plugins/converters/psx.xml
<?xml version="1.0"?>
<thepipeline  xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <converter prefix="ic" name="psx-tim" target="psx">
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="-o @" type="file"/>
            <param id="vpos" output="-org @[0] @[1]" type="vec[2]" description="Position of the texture in psx-vram"/>
            <param id="cpos" output="-plt @[0] @[1]" type="vec[2]" description="Position of the CLUT in the vram"/>
            <param id="bpp" output="-bpp @" type="strict-enum[4,8,16,24]" description="bits per color-information"/>
            <param id="alpha" output="-usealpha" type="bool" description="Use alpha"/> 
        </parameters>  
        <command toolid="img2tim" arguments="@@" extension="tim"/>
    </converter>

    <!-- ffmpeg -y -i raw/music/horn.wav -f s16le -ac 1 -ar 44100 tmp.dat -->
    <converter prefix="ac" name="psx-wav-format" target="psx">
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="@" type="file"/>
        </parameters>
        <command arguments="-y -i @[in] -f s16le -ac 1 -ar 44100 @[out]" toolid="ffmpeg" extension="wav"/>
    </converter>

    <!-- wav2vag tmp.dat vag/horn.vag -sraw16 -freq 44100 -->
    <converter prefix="ac" name="psx-vag-format">
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="@" type="file"/>
        </parameters>
        <command arguments="@[in] @[out] -sraw16 -freq 44100" toolid="wav2vag" extension="vag"/>
    </converter>
</thepipeline>

=== dertom95/thepipe/plugins/converters/irfanview.xml
<?xml version="1.0"?>
<thepipeline  xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tool id="irfanview" type="cli">
        <command host="win" file="@/../../tools/win/IrfanView/i_view64.exe"/>
        <command host="linux" file="@/../../tools/win/IrfanView/i_view64.exe" wrapper="wine"/>
    </tool>
    <!-- $(PIPECMD) /opt/tools/wine.sh /opt/tools/win_host/IrfanView/i_view64.exe $(WINE_ASSETS)\\palette\\AMIGA.bmp /export_pal=$(WINE_ASSETS)\\palette\\AMIGA.pal  /killmesoftly -->
    <converter name="createpalette" prefix="ic">
        <parameters>
            <param id="in" output="@" type="file" />
            <param id="out" output="@" type="file" />
        </parameters>
        <command arguments="@[in] /export_pal=@[out]  /killmesoftly" toolid="irfanview" extension="pal"/>
    </converter>

    <converter name="applypalette" prefix="ic">
        <parameters>
            <param id="in" output="@" type="file" />
            <param id="palette" output="@" type="file" />
            <param id="out" output="@" type="file" />
        </parameters>
        <command arguments="@[in] /import_pal=@[palette] /convert=@[out]  /killmesoftly" toolid="irfanview"/>
    </converter>

    <!-- <converter name="to-sfx" prefix="ac-atari" target="atari">
        <parameters>
            <param id="in" output="@"  type="file" />
            <param id="out" output="@" type="file"/>            
        </parameters>
        <command arguments="@[in] -r 2760 -c 1 -t u8 -D @[out]" toolid="sox" extension="sfx"/>
    </converter>     -->
</thepipeline>

=== dertom95/thepipe/plugins/converters/misc.xml
<?xml version="1.0"?>
<thepipeline  xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tool id="bin2c" type="cli">
        <command host="linux" file="@/../../tools/linux/bin2c"/>
    </tool>

    <!-- $(PIPECMD) /opt/tools/wine.sh /opt/tools/win_host/IrfanView/i_view64.exe $(WINE_ASSETS)\\palette\\AMIGA.bmp /export_pal=$(WINE_ASSETS)\\palette\\AMIGA.pal  /killmesoftly -->
    <converter name="bin-to-c" prefix="conv">
        <parameters>
            <param id="in" output="@" type="file" />
            <param id="out" output="@" type="file" />
            <param id="prefix" output="@" type="string"/>
        </parameters>
        <command arguments="@[in] @[out] @[file_wo_ext]" toolid="bin2c" extension="h"/>
    </converter>

</thepipeline>
