=== dertom95/thepipe/plugins/xsd/thepipeline.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://thepipeline.com" xmlns="https://thepipeline.com" elementFormDefault="qualified">
	<xs:simpleType name="tooltype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="cli"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="targettype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="psx"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="hosttype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="linux"/>
					<xs:enumeration value="linux-arm"/>
					<xs:enumeration value="macos"/>
					<xs:enumeration value="win"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="paramtype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="bool"/>
					<xs:enumeration value="enum[]"/>
					<xs:enumeration value="file"/>
					<xs:enumeration value="vec[2]"/>
					<xs:enumeration value="vec[3]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="booltype" final="restriction">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="false"/>
					<xs:enumeration value="true"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:element name="thepipeline">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="converter">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="command">
								<xs:complexType>
									<xs:attribute name="arguments" type="xs:string" use="required"/>
									<xs:attribute name="extension" type="xs:string"/>
									<xs:attribute name="metafiles" type="xs:string"/>
									<xs:attribute name="toolid" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="parameters">
								<xs:complexType>
									<xs:choice minOccurs="0" maxOccurs="unbounded">
										<xs:element name="param">
											<xs:complexType>
												<xs:attribute name="description" type="xs:string"/>
												<xs:attribute name="id" type="xs:string" use="required"/>
												<xs:attribute name="output" type="xs:string" use="required"/>
												<xs:attribute name="required" type="booltype"/>
												<xs:attribute name="type" type="paramtype" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="rip">
											<xs:complexType>
												<xs:attribute name="required" type="booltype"/>
												<xs:attribute name="type" type="paramtype" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="prefix" type="xs:string" use="required"/>
						<xs:attribute name="target" type="targettype"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="tool">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="command">
								<xs:complexType>
									<xs:choice minOccurs="0" maxOccurs="unbounded">
										<xs:element name="rip">
											<xs:complexType>
												<xs:attribute name="host" type="hosttype"/>
											</xs:complexType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="file" type="xs:string"/>
									<xs:attribute name="host" type="hosttype"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="target" type="targettype"/>
						<xs:attribute name="type" type="tooltype" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dertom95/thepipe/plugins/tools/compiler_tools.xml
<thepipeline xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tool id="vbcc6502" type="cli" target="6502">
        <command host="linux" wrapper="wine" file="/home/ttrocha/_dev/projects/retro/CrossEngine/Compiler/6502/vbcc6502/vbcc6502_win/vbcc/bin/vbcc6502.exe"/>
    </tool>

    <tool id="gcc" type="cli" target="linux">
        <command host="linux" file="/usr/bin/gcc"/>
    </tool>
    
    <converter prefix="compile" name="gcc" target="linux">
        <parameters>
            <param id="in" output="@" type="multifile" />
            <param id="out" expose="true" output="-o @" type="file"/>            
        </parameters>
        <command arguments="@@" toolid="gcc" />
    </converter>
</thepipeline>

=== dertom95/thepipe/plugins/converters/imagemagick.xml
<thepipeline  xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
    <tool id="convert" type="cli">
        <command host="linux" file="/usr/bin/convert"/>
    </tool>
    <tool id="montage" type="cli">
        <command host="linux" file="/usr/bin/montage"/>
    </tool>
    
    <converter prefix="ic" name="indexed"> 
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="@" type="file"/>
            <param id="colors" output="-colors @" type="number[0-255]" required="true" description="amount of colors" />
            <param id="dither" output="+dither" type="bool" description="dither result"/>
        </parameters> 
        <command toolid="convert" arguments="@[in] @@ @[out]" extension="png"/>
    </converter>

    <converter prefix="ic" name="rotate"> 
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="@" type="file"/>
            <param id="background" output="-background ''@'' -virtual-pixel ''background'' " type="enum[transparent,#rgb,#rrggbb,#rrggbbaa]"/>
            <param id="degree-keepsize" output="-distort SRT @" type="number[0-360]" description="rotate image degrees" />
            <param id="degree" output="-rotate @" type="number[0-360]" description="rotate image degrees" />
        </parameters> 
        <command toolid="convert" arguments="@[in] @@ @[out]" extension="png"/>
    </converter>

    <converter name="rescale" prefix="ic">
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="@" type="file"/>
            <param id="scale-xy" output="-resize @[0]x@[1]" type="vec[2]" />
            <param id="forcescale-xy" output="-resize @[0]x@[1]!" type="vec[2]" />
            <param id="scale-percent" output="-resize @%" type="number[0-100]" />
            <param id="forcescale-percent" output="-resize @%" type="number[0-100]" />
        </parameters>
        <command arguments="@[in] @@ @[out]" toolid="convert" />
    </converter>

    <converter prefix="ic" name="im-spritepacker">
        <parameters>
            <param id="in" output="@" type="multifile"/>
            <param id="out" output="@" type="file"/>
            <param id="tile" output="-tile @[0]x@[1]" type="vec[2]" />
            <param id="size" output="-geometry @[0]x@[1]+0+0" type="vec[2]"/>
        </parameters>
        <command arguments="@[in] @@ -background transparent @[out]" toolid="montage" extension="png"/>
    </converter>
</thepipeline>

=== dertom95/thepipe/plugins/converters/grit.xml
<?xml version="1.0"?>
<thepipeline  xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tool id="grit" type="cli">
        <command host="linux" file="@/../../tools/linux/gba/grit"/>
    </tool>

    
    <!-- $(PIPECMD) /opt/tools/wine.sh /opt/tools/win_host/IrfanView/i_view64.exe $(WINE_ASSETS)\\palette\\AMIGA.bmp /export_pal=$(WINE_ASSETS)\\palette\\AMIGA.pal  /killmesoftly -->
    <converter name="convert-tiles-256" prefix="ic" target="gba">
        <parameters>
            <param id="in" output="@" type="file" />
            <param id="out" output="@" type="file" />
        </parameters>
        <command arguments="@[in] -g -gB8 -gt -o @[out]" toolid="grit" extension="h" metafiles="@[temp_folder]/@[file_wo_ext].s"/>
    </converter>


    <converter name="convert-sprites-16" prefix="ic" target="gba">
        <parameters>
            <param id="in" output="@" type="file" />
            <param id="out" output="@" type="file" />
            <param id="transparent" output="-gT @" type="string" />
            <param id="sprite-width" output="-Mw @" type="string" required="true" description="in tilesize 8x8"/>
            <param id="sprite-height" output="-Mh @" type="string" required="true"  description="in tilesize 8x8"/>
        </parameters>
        <command arguments="@[in] -gB4 -p @@ -o @[out]" toolid="grit" extension="h" metafiles="@[temp_folder]/@[file_wo_ext].s"/>
    </converter>


</thepipeline>

=== dertom95/thepipe/plugins/converters/spritepacker.xml
<thepipeline  xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <converter prefix="ic" name="urho-spritepacker">
        <parameters>
            <param id="in" output="@" type="multifile"/>
            <param id="out" output="@" type="file"/>
            <param id="padding" output="-px @[0] -py @[1]" type="vec[2]" description="Adds x/y pixels of padding per image to width" />
            <param id="offset"  output="-ox @[0] -oy @[1]" type="vec[2]" description="Adds x/y pixels to the horizontal position per image"/>
            <param id="frame"   output="-frameWidth @[0] -frameHeight @[1]" type="vec[2]" description="Sets a fixed width/height for image and centers within frame"/>
            <param id="trim"    output="-trim" type="bool" description="Trims excess transparent space from individual images offsets by frame size"/>
            <!-- <param id="xmlfile" output="-xml @[0]" type="file" description="Generates an SpriteSheet xml file at path"/> -->
            <param id="debug"   output="-debug" type="bool" description="Draws allocation boxes on sprite"/>
        </parameters> 
        <command toolid="spritepacker" arguments="-xml @[temp-folder]@[mf-name].xml @@ @[in] @[out]" extension="png" metafiles="@[temp-folder]@[mf-name].xml"/>  
    </converter>
</thepipeline>

=== dertom95/thepipe/plugins/tools/ic_blender.xml
<thepipeline xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tool id="blender" type="cli">
        <command host="linux" file="/home/ttrocha/blender-git/build_linux/bin/blender"/>
    </tool>

    <converter prefix="blender" name="object-output" target="all">
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="@" type="file"/>
        </parameters>
        <command toolid="blender" arguments="--background @[in] --python /home/ttrocha/_dev/projects/python/thepipeline/tools/python/blender/output_objects.py -- --output-file @[out]"  extension="scene.objects.txt"/>        
    </converter>
 
</thepipeline>

=== dertom95/thepipe/plugins/converters/rg-TilEd.xml
<thepipeline xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tool id="rg-tiled-conversion" type="cli">
        <command host="linux" file="@/../../tools/linux/rg/TilEdConverter" />
    </tool>

    <converter name="convert-tiled-map" prefix="rg">
        <parameters>
            <param id="in" output="@"  type="file" />
            <param id="compression" output="-compress" type="bool"/>
            <param id="out" output="@" type="file"/>            
        </parameters>
        <command arguments="@[in] @@" toolid="rg-tiled-conversion" extension="map"/>
    </converter>

    <converter name="convert-tiled-tileset" prefix="rg">
        <parameters>
            <param id="in" output="@"  type="file"/>
            <param id="out" output="@" type="file"/>            
        </parameters>
        <command arguments="@[in] -tileset @[out]" toolid="rg-tiled-conversion" extension="ts"/>
    </converter>


</thepipeline>

=== dertom95/thepipe/plugins/converters/gfxconvert.xml
<thepipeline xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tool id="GFXConv" type="cli">
        <command host="linux" file="@/../../tools/linux/rg/GFXConvert"/>
    </tool>

    <!-- $(PIPECMD) /opt/tools/wine.sh /opt/tools/win_host/IrfanView/i_view64.exe $(WINE_ASSETS)\\palette\\AMIGA.bmp /export_pal=$(WINE_ASSETS)\\palette\\AMIGA.pal  /killmesoftly -->
    <converter name="convert-sprites" prefix="rg">
        <parameters>
            <param id="in" output="@" type="file" />
            <param id="out" output="@" type="file" />
            <param id="palette" output="@" type="file" />
        </parameters>
        <command arguments="sprite @[target] @[in] @[out] @[palette]" toolid="GFXConv" extension="bin"/>
    </converter>

    <converter name="convert-tileset" prefix="rg">
        <parameters>
            <param id="in" output="@" type="file" />
            <param id="out" output="@" type="file" />
            <param id="palette" output="@" type="file"  />

        </parameters>
        <command arguments="tileset @[target] @[in] @[out] @[palette]" toolid="GFXConv" extension="bin"/>
    </converter>

</thepipeline>

=== dertom95/thepipe/plugins/converters/psxtim.xml
<?xml version="1.0"?>
<thepipeline  xmlns="https://thepipeline.com" xsi:schemaLocation="https://thepipeline.com ../xsd/thepipeline.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <converter prefix="ic" name="psx-tim" target="psx">
        <parameters>
            <param id="in" output="@" type="file"/>
            <param id="out" output="-o @" type="file"/>
            <param id="vpos" output="-org @[0] @[1]" type="vec[2]" description="Position of the texture in psx-vram"/>
            <param id="cpos" output="-plt @[0] @[1]" type="vec[2]" description="Position of the CLUT in the vram"/>
            <param id="bpp" output="-bpp @" type="enum[4,8,16,255]" description="bits per color-information"/>
            <param id="alpha" output="-usealpha" type="bool" description="Use alpha"/> 
        </parameters>  
        <command toolid="img2tim" arguments="@@" extension="tim"/>
    </converter>
</thepipeline>
